# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: oracle_enhanced
  database: XE
  username: bboard
  password: bboard

memp_production:
  adapter: oracle_enhanced
  database: XE  
  username: memp
  password: memp

opac_production:
  adapter: oracle_enhanced
  database: XE  
  username: opac
  password: opac


webstore_production:
  adapter: oracle_enhanced
  database: XE  
  username: webstore
  password: webstore

production:
  adapter: oracle_enhanced
  database: XE  
  username: bboard
  password: bboard




