# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: oracle_enhanced
  database: XE
  username: memp_etl
  password: memp_etl

test:
  adapter: oracle_enhanced
  database: XE
  username: test_bboard
  password: test_bboard


production:
  adapter: oracle_enhanced
  database: XE
  username: bboard_staging
  password: bboard_staging

etl_execution:
  adapter: oracle_enhanced
  database: XE
  username: bboard_staging
  password: bboard_staging

memp_development:
  adapter: oracle_enhanced
  database: XE
  username: memp
  password: memp


opac_development:
  adapter: oracle_enhanced
  database: XE 
  username: opac
  password: opac


webstore_development:
  adapter: oracle_enhanced
  database: XE
  username: webstore
  password: webstore
