# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: oracle_enhanced
  database: staging
  username: bboard
  password: bboard

production:
  adapter: oracle_enhanced
  database: staging
  username: bboard
  password: bboard


memp_production:
  adapter: oracle_enhanced
  database: staging
  username: memp
  password: memp

opac_production:
  adapter: oracle_enhanced
  database: staging 
  username: opac
  password: opac


webstore_production:
  adapter: oracle_enhanced
  database: staging
  username: webstore
  password: webstore




